

service: thekittens-crud


provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:service}-kittens-${opt:stage}

  environment:
    DYNAMODB_KITTEN_TABLE: ${self:service}-kittens-${opt:stage}

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: kitten
          method: post
  list:
    handler: handler.list
    events:
      - http:
          path: kitten
          method: get
  get:
    handler: handler.get
    events:
      - http:
          path: kitten/{name}
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: kitten/{name}
          method: put
  delete:
    handler: handler.update
    events:
      - http:
          path: kitten/{name}
          method: delete

resources:
 Resources:
    kittenTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:service}-kittens-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
